### ISSUE TITLE
Arrow functions on event break syntax highlighting

### ISSUE THREAD

**Issue by mflamey** [vuejs/vue-syntax-highlight#101]
When using an arrow function in an event, it breaks syntax highlighting for the rest of the file
![screenshot_12](https://user-images.githubusercontent.com/31272718/29605587-b68d85ca-87eb-11e7-839d-2d76f9a58188.png)

**Comment by andreixk** [comment]
Same issue. Found a (sort of) workaround: to include { } around the function code, although it should be optional
<img width="1085" alt="screen shot 2017-09-03 at 14 05 00" src="https://user-images.githubusercontent.com/17452117/30005456-0ad35e16-90b1-11e7-9ccb-067aad0abe73.png">

**Comment by nightpool** [comment]
Yep, just found the same thing.

![image](https://user-images.githubusercontent.com/233815/30822637-71c89634-a1f7-11e7-99fb-60d46fad1e86.png)

**Comment by gtalarico** [comment]
Came here to report this :) Adding brackets fixes it for now.

![image](https://user-images.githubusercontent.com/9513968/32361372-0bff5ea2-c036-11e7-9a1b-94a3488c53fb.png)


![image](https://user-images.githubusercontent.com/9513968/32361365-060d266e-c036-11e7-8df0-379f2a71016a.png)

**Comment by Thom1729** [comment]
This is probably the same problem as #107.

**Comment by skyronic** [comment]
This is fixed in the upcoming release.
