### ISSUE TITLE
The problem with syntax highlighting when using @extend in .sass

### ISSUE THREAD

**Issue by letehaha** [vuejs/vue-syntax-highlight#103]
A little problem with syntax highlighting when we using `@extend` in `.sass`. 
<img width="451" alt="screen shot 2017-09-13 at 11 59 01 pm" src="https://user-images.githubusercontent.com/12257282/30400451-95febbd0-98df-11e7-88a5-48e8d8adade6.png">

**Comment by skyronic** [comment]
This is working fine on the latest version. We are still waiting for [the PR](https://github.com/wbond/package_control_channel/pull/6799) to be merged with package control. 

You can try with cloning the repo into `Packages` folder and using latest sublime dev build and re-open with a sample .vue file if the problem persists. Thank you!
