### ISSUE TITLE
Using syntax prevent linting of <template> with sublimeLinter and eslint 

### ISSUE THREAD

**Issue by iamsisar** [vuejs/vue-syntax-highlight#104]
In SublimeText 3, when `Vue Component` is selected as syntax, sublimeLinter cannot access `<template>`. Switching syntax to `Javascript (Babel)` makes it work again.

Please note the missing error for rule `no-textarea-mustache` at line 4.

| *syntax: Vue Component* | *syntax: Javascript (Babel)* |
|---------------------------|-----------------------------|
|![vue](https://user-images.githubusercontent.com/6459637/31284969-5cc4b972-aaba-11e7-94a7-d800b55adbb6.jpg)|![babel](https://user-images.githubusercontent.com/6459637/31284978-60dfefae-aaba-11e7-8c2a-b68de095417c.jpg)|

*.eslintrc*

```
{
    "extends": [
        "semistandard",
        "plugin:vue/recommended"
    ]
}
```

**Comment by exophunk** [comment]
Any news or workarounds for this?

**Comment by skyronic** [comment]
I just checked and it seems to be working for me:

![image](https://user-images.githubusercontent.com/80173/39846314-e6aa014e-53c8-11e8-8891-157fc240d471.png)

I set `linters` config to:

```
	"linters":
	{
		"eslint": {
			"selector": "text.html.vue, source.js - meta.attribute-with-value"
		}
	}
```

as specified in the [documentation](https://github.com/SublimeLinter/SublimeLinter-eslint#using-eslint-with-plugins-eg-vue)

My `eslintrc.js` is the default one from the webpack example.

```
// https://eslint.org/docs/user-guide/configuring

module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint'
  },
  env: {
    browser: true,
  },
  extends: [
    // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
    // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
    'plugin:vue/essential', 
    // https://github.com/standard/standard/blob/master/docs/RULES-en.md
    'standard'
  ],
  // required to lint *.vue files
  plugins: [
    'vue'
  ],
  // add your custom rules here
  rules: {
    // allow async-await
    'generator-star-spacing': 'off',
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
  }
}
```

Please note this is with the latest version on git. We will be releasing a new version shortly with these fixes. Please re-open the issue if you continue to find issues with this.
