### ISSUE TITLE
v-bind shorthand breaks formatting

### ISSUE THREAD

**Issue by benjarwar** [vuejs/vue-syntax-highlight#105]
Using the [v-bind shorthand](https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand), in which only a colon is used like `:attribute` instead of `v-bind:attribute`, breaks the rest of the formatting in the file.

**Comment by peterecho** [comment]
I am seeing the same issue.

**Comment by skyronic** [comment]
This is working fine now. I am going to go ahead and close this issue. Please reopen if you continue experiencing problems.

![image](https://user-images.githubusercontent.com/80173/39841371-83bbfed8-53b0-11e8-819e-6761a7da221e.png)
