### ISSUE TITLE
Support self-closing component tags

### ISSUE THREAD

**Issue by kjakobson** [vuejs/vue-syntax-highlight#106]
When trying to auto-close the div element

`<div><my-component/>
`

resolves to

`<div><my-component/></my-component>`

It should close the div tag.

Self-closing tags are now part of Vue code styleguide. I believe this issue is similar to HTML syntax, resolved by this PR: https://github.com/sublimehq/Packages/pull/971.

**Comment by yyx990803** [comment]
Auto-completion is not handled by and cannot be changed by this package, it's simply using the same expand rules as HTML.

**Comment by Herteby** [comment]
What's strange though is that in Sublime Text (Build 3143, the latest) self-closing tags work correctly in .html files, but not in .vue files (using Vue Syntax Highlight 3.2.3)

**Comment by Herteby** [comment]
Actually this package *does* control autocompletion, indirectly, in the same way as that PR fixed it for basic HTML.
This commit seems to have (accidentally?) fixed this issue https://github.com/vuejs/vue-syntax-highlight/commit/17139a34b31a163374a083143418df077074b1e6

**Comment by skyronic** [comment]
@Herteby 17139a3 should technically not affect 3143. Only 3153 onwards. Lemme know if you notice any odd behaviours.

**Comment by Jarwain** [comment]
Relevant issue (it *should* already be fixed) https://github.com/SublimeTextIssues/DefaultPackages/issues/176
