### ISSUE TITLE
What is the color scheme in the image of readme.md

### ISSUE THREAD

**Issue by condef5** [vuejs/vue-syntax-highlight#111]
Plesae, I search the name color scheme of this [image](https://cloud.githubusercontent.com/assets/499550/11458853/99ed23aa-9696-11e5-9bf6-43c706487aee.png).

**Comment by Herteby** [comment]
I believe it's Evan You's custom version of https://github.com/equinusocio/material-theme
I've made a similar theme myself: https://github.com/Herteby/Super-Monokai

**Comment by yyx990803** [comment]
It was from an old version of Material Theme, but yeah it's Material Theme.
