### ISSUE TITLE
Version 4.0.0

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vue-syntax-highlight#112]
I see there's a new release. I've been looking forward to it. If it's ready for general release, can we get a consistent version number update to `4.0.0`, and then make sure that is the version on the package control website:

* https://packagecontrol.io/packages/Vue%20Syntax%20Highlight

![Current release numbers showing inconsistent recent naming of releases](https://user-images.githubusercontent.com/4629794/34047543-39b7bdba-e176-11e7-9b4b-0a8d1a930e18.png)

**Comment by yyx990803** [comment]
The new version and old versions are published in parallel because the new version only works in a newer build of Sublime. We are waiting for [this PR](https://github.com/wbond/package_control_channel/pull/6799) to be merged.
