### ISSUE TITLE
Incorrect highlighting for directives with arguments/modifiers

### ISSUE THREAD

**Issue by Herteby** [vuejs/vue-syntax-highlight#113]
@skyronic Found a bug with the new version

Directives with arguments/modifiers do not get their content treated as JS.
![image](https://user-images.githubusercontent.com/6474685/34207241-f96d4604-e589-11e7-92c1-5030fc7e2a83.png)

**Comment by skyronic** [comment]
Thanks for reporting this I'll have it fixed this week.

**Comment by skyronic** [comment]
Hey @Herteby it's fixed now will merge it in along with some other patches.

![image](https://user-images.githubusercontent.com/80173/34819878-02b8cbae-f6e5-11e7-99e2-202f7dcd468f.png)

**Comment by skyronic** [comment]
Hello this has been fixed and I can confirm is working correctly in a new version we are releasing soon. Please try it out and reopen this issue if you continue facing issues.
