### ISSUE TITLE
Incorrect highlighting when element has multiple directives

### ISSUE THREAD

**Issue by Herteby** [vuejs/vue-syntax-highlight#114]
@skyronic Found another bug

![image](https://user-images.githubusercontent.com/6474685/34256385-4ebc7e74-e655-11e7-99c3-95e3bb40b31d.png)

**Comment by skyronic** [comment]
Wow. Great catch, but should be an easy fix. Will have it fixed in the weekend. Keep 'em coming!

**Comment by skyronic** [comment]
I thought this was a simple fix but I'm beginning to suspect this might be an issue with sublime text itself.

I've filed an issue sublimehq/Packages#1385 for now, otherwise I'll try to find a workaround if the dev build is released as stable before then.
