### ISSUE TITLE
Incorrect highlighting for object spread operator

### ISSUE THREAD

**Issue by Herteby** [vuejs/vue-syntax-highlight#115]
@skyronic Got another one for you!

**Babel syntax highlighter** - correct
![image](https://user-images.githubusercontent.com/6474685/34260314-bd695418-e665-11e7-9a71-a7f05f3ee84b.png)

**Vue syntax highlighter** - incorrect
![image](https://user-images.githubusercontent.com/6474685/34260297-abe2343a-e665-11e7-9293-a53b063639c1.png)

**Comment by skyronic** [comment]
Hey @Herteby. From what I can make out, this is an issue with sublime's JavaScript package. You should possibly file an issue with sublimehq/Packages repo.

**Comment by Herteby** [comment]
@skyronic Ah, that makes sense. And actually it's still in the proposal stage, which is probably why the default highlighter doesn't support it yet.

I figured out a solution though! Even though I had Babel set as the highlighter for .js files, it was using the default highlighter for js in .vue files. However, if you disable the JavaScript package, that forces it to switch to the Babel highlighter!
