### ISSUE TITLE
Incorrect highlighting with two mustache tags on the same row

### ISSUE THREAD

**Issue by Herteby** [vuejs/vue-syntax-highlight#116]
@skyronic Found another one for you
When two mustache tags are on the same row, the second one doesn't get syntax highlighting.
![image](https://user-images.githubusercontent.com/6474685/34478586-01c0cce6-efa2-11e7-8b3c-94420a4df860.png)

**Comment by skyronic** [comment]
this is also related to sublimehq/Packages#1385 and can't be fixed from our end right away :(

**Comment by skyronic** [comment]
This is working properly now. We will be releasing a new version soon which should have this fixed.

I'm closing this issue now, please feel free to re-open the issue if you continue experiencing problems.

![image](https://user-images.githubusercontent.com/80173/39842114-431fefc6-53b3-11e8-86ac-83a4458951c1.png)
