### ISSUE TITLE
Incorrect highlighting when using ES6 Arrow Function 

### ISSUE THREAD

**Issue by tom4dev** [vuejs/vue-syntax-highlight#118]
As you can see, using `ES6 arrow function` in event handler breaks the syntax highlight.
<img width="329" alt="capture d ecran 2018-01-10 a 13 44 44" src="https://user-images.githubusercontent.com/3238312/34773580-8275c6e6-f60c-11e7-97d1-350f51c7286c.png">

**Comment by Thom1729** [comment]
I could not reproduce this with the following code:

```
<div @click="(e) => { return true; }"></div>
<div @click="e => true"></div>
```

Are you using a third-party JavaScript syntax?

**Comment by Relequestual** [comment]
Hi. I'm experiencing this or similar issue, but without braces around the arrow...

![screen shot 2018-02-08 at 16 42 40](https://user-images.githubusercontent.com/731158/35985706-26de114a-0cef-11e8-8d34-033e9ec893d5.png)

Syntax is indeed set to vue component.

**Comment by Thom1729** [comment]
The problem there starts on line 3: `<form-table` is wrong. Are you using the latest version of this package on Sublime dev build 3157? Are you using the built-in JavaScript syntax as opposed to any third-party syntax?

**Comment by Relequestual** [comment]
I'm using build 3143.
Using the this package, version 3.2.4
(ST doesn't seem to think there's an available update... =/ )

I do have a bable version of the JavaScript syntax highlighter, but I'm using the Vue Component syntax highlighter. 
Opening a .js file uses the build-in JavaScript syntax highlighter.

**Comment by Thom1729** [comment]
The current version of this package's syntax relies on a feature that was added in build 3153. Hopefully, there will be a stable release soon.

**Comment by Relequestual** [comment]
Hashed Syntax Highlighting ? Looks interesting.

Fair enough. Hopefully they will release soon!
Doesn't look like they have a public release schedule =/

**Comment by Thom1729** [comment]
Specifically, the new syntax uses `embed`, which should improve performance given all of the various syntaxes that might be included within a Vue component.

**Comment by borela** [comment]
@Relequestual @tom4dev  Try https://github.com/borela/naomi after installing it, Vue will use FJSX15 to highlight javascript code + it supports some stage-0 features.

**Comment by skyronic** [comment]
Hello, this is working fine now. We are releasing a new version soon with support for the stable version of sublime text (3.1/3170)

![image](https://user-images.githubusercontent.com/80173/39841512-f8b08dd0-53b0-11e8-8ac8-7edda9b7f889.png)

Please do reopen this issue if you continue experiencing problems with arrow functions.
