### ISSUE TITLE
When attribute and variable name contains numbers, syntax highlight goes wild

### ISSUE THREAD

**Issue by Rayraegah** [vuejs/vue-syntax-highlight#120]
![image](https://user-images.githubusercontent.com/1559650/34944018-4ff52296-fa41-11e7-8613-e877d9fb54da.png)

**Comment by skyronic** [comment]
Thank you for reporting. I'll try to have this fixed asap

**Comment by Thom1729** [comment]
I could not reproduce this. The following was highlighted correctly:

```
<video-player
    class="video-player"
    v-if="nowPlaying"
    :key="nowPlaying.key"
    :hlsUrl="nowPlaying.high_hls_video"
    :mp4Url="nowPlaying.mixed_video"
    :poster="nowPlaying.thumbnail_url"
/>
```

**Comment by skyronic** [comment]
Hello,

Sorry for not following up on this sooner. I can confirm that this seems to work ok with the latest updates. We are releasing a new version soon, which works fine with numbers in the attributes. Please feel free to reopen if you continue experiencing issues.

![image](https://user-images.githubusercontent.com/80173/39841666-92493d84-53b1-11e8-9126-0b4bffa47874.png)
