### ISSUE TITLE
Handling multiple embeds in sublime

### ISSUE THREAD

**Issue by skyronic** [vuejs/vue-syntax-highlight#122]
(Opening issue for sake of discussion)

Some issues ( #114 and #116 ) were reported and this is a bug with sublime, which has been logged with sublime but assigned minor severity SublimeTextIssues/Core#2159. This isn't much of an issue for sublime but will basically make the vuejs syntax unusable.

My availability will be a bit on and off the coming 3 weeks, so I want to revert back to using an older approach. We have two options now, wanted to get your inputs @yyx990803 

* Option 1: Continue with this approach and wait till sublime fixes this issue.
* Option 2: Re-do some parts of the syntax with an alternate approach which is known to have no issues.

@Thom1729 would appreciate your thoughts on this. I think we can use `embed`/`extend` for script tags and CSS, but for this, I think we have to use `push`/`with_prototype` for the directives.

**Comment by Thom1729** [comment]
> I think we can use `embed`/`extend` for script tags and CSS, but for this, I think we have to use `push`/`with_prototype` for the directives.

That's what I would try, myself. It should work just fine. The downside, of course, is losing the efficiency gain of `embed`, but a working syntax is more important. The change is pretty minor, all things considered.

**Comment by yyx990803** [comment]
@skyronic thanks for the suggestions - I agree with temporarily switching to the `push/with_prototype` for directives until Sublime fixes the issue.

**Comment by skyronic** [comment]
@yyx990803 Sounds good.

@Thom1729 I'm currently unable to commit any time to this for about 4-5 days due to some personal work. If you've got some time free, and you're interested to replace it with `push`/`with_prototype` and send a PR or even a snippet of what you'd consider a good approach, I'll definitely test it thoroughly and merge it!

**Comment by Thom1729** [comment]
FYI, the embed bug was fixed in build 3157, so someone can go ahead and undo that patch.

**Comment by skyronic** [comment]
This has been resolved.
