### ISSUE TITLE
SCSS Highlight ; error

### ISSUE THREAD

**Issue by vanderlin** [vuejs/vue-syntax-highlight#126]
This error showed up the other day, with latest update. Thoughts?

![image](https://user-images.githubusercontent.com/149997/35543499-71d7fb3e-0533-11e8-90f5-a625cdc997e3.png)

**Comment by JosephusPaye** [comment]
Hi @vanderlin,

Had the same issue today. Solved it by following the suggestions in #52, specifically this comment: https://github.com/vuejs/vue-syntax-highlight/issues/52#issuecomment-285162761.

Hope that helps.

**Comment by z3nz** [comment]
Pretty easy fix. Just need to change this [line](https://github.com/vuejs/vue-syntax-highlight/blob/6cf71585a0c353576bee249fe6eaa7dad4231c8c/Vue%20Component.sublime-syntax#L699) to `embed: scope:source.scss` for the new branch.

**Comment by assembledadam** [comment]
Same issue here.

**Comment by luxueyan** [comment]
Same too。 mark

**Comment by skyronic** [comment]
This has been resolved, a new version will be released soon which will fix this issue.
