### ISSUE TITLE
Event binding shorthand doesn't highlight

### ISSUE THREAD

**Issue by rbrtmrtn** [vuejs/vue-syntax-highlight#129]
If you use the `@` shorthand for binding events, e.g. `@click="foo"`, the attribute isn't highlighted properly.

![image](https://user-images.githubusercontent.com/1463553/36560457-99ffee88-17c5-11e8-9e4c-1a446f5a178e.png)

**Comment by skyronic** [comment]
This is working now. A new release will be made available soon with support for latest stable sublime. Please do re-open the issue if you continue experiencing issues.

![image](https://user-images.githubusercontent.com/80173/39841436-b58cf020-53b0-11e8-8ca9-d69e4011e2db.png)
