### ISSUE TITLE
Spread operator is breaking syntax

### ISSUE THREAD

**Issue by Rozkalns** [vuejs/vue-syntax-highlight#133]
Please see image attached. Seems like Spread operator is breaking the syntax within methods block.

![compare](https://user-images.githubusercontent.com/8157701/37083941-c318b8ac-21f9-11e8-9cf2-25239f382b6a.png)

If you are not fixing code for Sublime Dev Builds, then you might close this.

PS, just realized that I left a mistake (double method definition), but it is not breaking stuff. I had to disable eslint, because it was quite glitchy past days as well.

**Comment by yyx990803** [comment]
Strangely, spread works fine for me with the exact same build of Sublime Text Dev (3157)
<img width="836" alt="screen shot 2018-03-07 at 10 40 41 am" src="https://user-images.githubusercontent.com/499550/37101629-06e2e590-21f4-11e8-8b06-6071b23a4b07.png">
.

**Comment by Rozkalns** [comment]
@yyx990803 Thanks for letting me know that you have atleast everything okay. Maybe I've messed up my Sublime Text settings. Will try later to wipe everything and start fresh. Otherwise: 

![spread-compare](https://user-images.githubusercontent.com/8157701/37102374-61a8df84-2230-11e8-966b-1bf21e5b214c.png)

Will let you know later how does it look then.

**Comment by Rozkalns** [comment]
@yyx990803 Unfortunately there are some issues with the syntax highlighter.

I did download fresh Sublime Text, removed `~/Library/Application Support/Sublime Text 3` - did not help.

Vue:
<img width="1092" alt="screen shot 2018-03-09 at 18 26 02" src="https://user-images.githubusercontent.com/8157701/37217924-950fbb2a-23c7-11e8-8684-7abe3cd7f6ee.png">

Babel:
<img width="1092" alt="screen shot 2018-03-09 at 18 26 09" src="https://user-images.githubusercontent.com/8157701/37217930-9cf3a112-23c7-11e8-9efe-795beeef8414.png">

**Comment by yyx990803** [comment]
You probably need to:

1. Set Babel as the default for js files
2. Disable the built-in JavaScript package.

**Comment by Rozkalns** [comment]
@yyx990803 Did what you said, it seemed still a bit not good, but once installed Ayu theme back on - it was OK after your steps! Thanks!

![image](https://user-images.githubusercontent.com/8157701/37221818-cf6e905a-23d3-11e8-9eb0-12e9b256bb4e.png)
