### ISSUE TITLE
[Not sure] CSS Style from external file with inline close tag brokes the next style tag

### ISSUE THREAD

**Issue by Juanmabs22** [vuejs/vue-syntax-highlight#134]
Hello!

If you use the auto close syntax for import a external file (css/sass/stylus) the next tag is broken.
I'm not sure if this is not the correct form to add (i think not, but works and it's more pretty).

![image](https://user-images.githubusercontent.com/5569316/37826629-77abc678-2e94-11e8-9bc0-505c533efbc8.png)

Thanks!

**Comment by samuraime** [comment]
I have a same issue
<img width="453" alt="screen shot 2018-04-12 at 9 47 46 pm" src="https://user-images.githubusercontent.com/2203205/38681414-34a3c0d0-3e9b-11e8-9a85-67b04d881394.png">

**Comment by skyronic** [comment]
This has been fixed in #140, will be released soon.
