### ISSUE TITLE
Recently updated?In the <style lang=''> grammar block no highlight

### ISSUE THREAD

**Issue by Wulawa** [vuejs/vue-syntax-highlight#137]
<img width="278" alt="wx20180507-192136 2x" src="https://user-images.githubusercontent.com/23315835/39699480-fa39704e-522b-11e8-9e35-b51913aa4289.png">
<img width="291" alt="lang" src="https://user-images.githubusercontent.com/23315835/39699662-be10399e-522c-11e8-8d5d-b708d66bb8a3.png">
No Lang property is normal

**Comment by skyronic** [comment]
This has been fixed, extension will be updated shortly.
