### ISSUE TITLE
Switch primary branch to `next`.

### ISSUE THREAD

**Issue by Thom1729** [vuejs/vue-syntax-highlight#144]
Since 3.1 is out, it's probably time to set `next` as the main branch rather than `master`.

**Comment by yyx990803** [comment]
Unfortunately GitHub linguist uses this repo for syntax highlighting Vue files on GitHub, and it does not support the new syntax, so we have to keep the default branch the old version.

**Comment by yyx990803** [comment]
Or maybe we should move the new syntax to a different repo...

**Comment by skyronic** [comment]
@yyx990803 Looks like linguist picks up `.yaml-tmlanguage` files too.

https://github.com/github/linguist/blob/a7f835a653864922988c4aa6a6d4440c35a48acf/tools/grammars/compiler/loader_fs.go#L23

I can try to run linguist locally and see if it formats with the old yaml `tmLanguage`. This will be used by linguist but sublime should hopefully ignore the yaml version of `tmLanguage`

Then we can use a single branch.
