### ISSUE TITLE
Sass syntax highlight not working on 3.3.1

### ISSUE THREAD

**Issue by mateuscruz** [vuejs/vue-syntax-highlight#146]
Hey guys,

Just figured I should let you know that Sass syntax highlight has not been working ever since the `3.3.1` update (at least for me), as you can see in the screenshot below:
![screenshot from 2018-05-22 13-39-04](https://user-images.githubusercontent.com/8962842/40376766-92e17e3c-5dc5-11e8-86b6-ca5297abe590.png)

Everything else seems to be fine, though.
Thanks!

**Comment by skyronic** [comment]
do you have the sass extension?

![image](https://user-images.githubusercontent.com/80173/40378284-1854bd68-5dc1-11e8-88cd-95f1b66a8a4b.png)

The SCSS extension doesn't seem to work effectively but SASS extension has full support.

**Comment by mateuscruz** [comment]
Thank you, @skyronic! That did the trick for me.
