### ISSUE TITLE
Vue-Syntax-Highlight not appearing in Package Control

### ISSUE THREAD

**Issue by p3lican** [vuejs/vue-syntax-highlight#151]
- Using Sublime 3.0 Build 3143

- Searching "vue", "vue syntax highlight", or "vue-syntax-highlight" doesn't show vue syntax highlight.

I have other vue packages but they don't work with scss.

Has this been removed from Package Control?

**Comment by francislavoie** [comment]
It appears for me... Do you already have it installed? Search your `remove` list.

**Comment by skyronic** [comment]
I'm not sure why this might be the case. Can you test with an updated version of sublime?

**Comment by skyronic** [comment]
I checked multiple versions of sublime text and it seems to be working fine. I am closing the issue for now, please re-open if there's additional information you have. Thank you.
