### ISSUE TITLE
Curly braces in a v-bind directive breaks highlighting

### ISSUE THREAD

**Issue by mbloch** [vuejs/vue-syntax-highlight#156]
Example:
![image](https://user-images.githubusercontent.com/1232222/43216930-3c7efe90-900e-11e8-8316-4c0779bf7104.png)

The same error occurs using the longhand form (`v-bind:to=` instead of `:to=`)

* Using the most recent commit on master, cf1e82d90a0bb2228bdf0afb2bbfb0d30ea70a86)
* Using Sublime 3.0 build 3175 on MacOS 10.13.6

**Comment by skyronic** [comment]
Sorry for the delayed reply.

Can you use branch `new`? We have a note in the readme that we don't support `master` on newer releases. 

I can't seem to repro this on `new`

![image](https://user-images.githubusercontent.com/80173/47883213-9ec7df80-de02-11e8-935f-0a0912758324.png)
