### ISSUE TITLE
How to use this plugin

### ISSUE THREAD

**Issue by spfund** [vuejs/vue-syntax-highlight#158]
Hello,

I've installed the package to Sublime Text 3.1.1, but the **.vue** files (with <template, <script> and <stylescoped>) still looking like before, all plain text in black. What I'm missing? 

Thanks in advance

**Comment by LinusBorg** [comment]
There's nothing else to do than install it, there's no additional step.

**Comment by spfund** [comment]
Yep, I just found out when I create a NEW **.vue** file, then it works. But the "old" **.vue** files (that were already opened with Sublime) still have no highlighting... even when I restart Sublime or the computer.

However, thanks. I think this can be closed, it's not an issue.

**Comment by naguibihab** [comment]
Shouldn't this be fixed? Otherwise, I can't use this plugin for my existing projects.
