### ISSUE TITLE
Not working with SCSS syntax in ST3 Build 3176

### ISSUE THREAD

**Issue by Aventus** [vuejs/vue-syntax-highlight#161]
If I understood correctly, this package works with github.com/braver/SublimeSass and sass highlight works fine, but when I switch to lang="scss" syntax is broken

![2018-10-31_101017](https://user-images.githubusercontent.com/3983526/47774271-34754900-dcf5-11e8-844c-69c9416d4023.png)

**Comment by vapurrmaid** [comment]
See the issue I created https://github.com/braver/SublimeSass/issues/15

SublimeSass recently switched to a different fork that got it's first push.  Among the changes was the `scope` of  from `source.scss` to `source.css.scss`.

It looks like we'll have to wait for `vue-syntax-highlight` to update their `scss` scope to match it.

https://github.com/vuejs/vue-syntax-highlight/blob/cf1e82d90a0bb2228bdf0afb2bbfb0d30ea70a86/vue.YAML-tmLanguage#L177

A workaround is to disable SublimeSass and use the old package, which is available [here](https://packagecontrol.io/packages/Syntax%20Highlighting%20for%20Sass)

**Comment by rchl** [comment]
Another workaround:
- Install https://packagecontrol.io/packages/PackageDev
- Extract and Open `Vue Syntax Highlight` package
- Modify relevant part of tmLanguage file (change `source.scss` to `source.css.scss`)

**Comment by skyronic** [comment]
A new release has been pushed out. Can you try to update it and let me know if the issue persists?

**Comment by domstubbs** [comment]
That’s fixed it for me, thanks!

**Comment by vapurrmaid** [comment]
![1](https://user-images.githubusercontent.com/11184711/47913033-edac5e00-de70-11e8-9d4a-352b14ca1baf.PNG)
![2](https://user-images.githubusercontent.com/11184711/47913034-ee44f480-de70-11e8-9a2c-7d81507bf4bb.PNG)

**Comment by thariddler** [comment]
So you want to tell me that from now long I need to install some shady plugin to use SCSS with Vue? Why are you killing it?

**Comment by thariddler** [comment]
Vue ecosystem is turning into pile of chaos.

**Comment by thariddler** [comment]
I used this for SCSS highlightning - https://packagecontrol.io/packages/SCSS

All was working just fine. 
Now you are telling me that I need to use some fucking braver plugin for that? Rly???

**Comment by vapurrmaid** [comment]
This is the last I'll respond to this especially given that I run neither of these packages and am just trying to help

1. Braver's plugin is the official one and has more user's that that. Just check it out: https://packagecontrol.io/packages/Sass

2. It is also the package Vue Syntax Highlighting suggested before anyways

3. The package you linked hasn't been updated for 4 years....

4. You can ask the maintainer of that plugin to update the `scope` and all will work again, though based on the maintenance it receives, I don't think it's likely

**Comment by dgirgenti** [comment]
If this package (vue-syntax-highlight) _explicitly requires_ a _specific_ external package, it needs to be listed somewhere, or better yet, included as a dependency. This issue being closed, I had to hunt down why my SCSS was no longer being highlighted. I personally use a Sublime Package for SCSS that has been working for **years**, even in .vue files, and it no longer works.

**Comment by skyronic** [comment]
A new update has been pushed out and previously supported SCSS packages should work again. Do let me know if you continue experiencing issues.

**Comment by cmcleese** [comment]
I'm currently using :

- braver/SublimeSass - v2.1.1
- vuejs/vue-syntax-highlight  - v3.3.3

`<style lang="scss">`   = no highlight
`<style lang="sass">`   = no highlight
`<style lang="css">`     = yes highlight

**Comment by darwinluague** [comment]
Removing braver/SublimeSass and installing it again fixes mine.
