### ISSUE TITLE
SCSS no longer being highlighted in Vue SFCs

### ISSUE THREAD

**Issue by dgirgenti** [vuejs/vue-syntax-highlight#164]
As of the most recent update to this package, SCSS is no longer being highlighted in any way within `<style lang="scss">` tags. It is completely white in all of my .vue files.

![image](https://user-images.githubusercontent.com/1879070/47916228-d888fc80-de7b-11e8-9c09-bf3eead08091.png)

If I do a `<style lang="css">` or just `<style>`, it is working but only for CSS (not SCSS).

**Comment by dgirgenti** [comment]
Seems it is likely related to bc432742a6cf1c53fb3f93f9b87cc7f217dae328

**Comment by dgirgenti** [comment]
Thanks for consolidating all this info @vapurrmaid ! I think updating the docs/readme might be in order, since I imagine a large number of people want proper SCSS highlighting in Vue.

**Comment by vapurrmaid** [comment]
I agree, although from my reading of the information, contributors should ask other Sass/Scss packages to see if they think updating the `scope` is a good idea. If other packages do, then one can remain free in their choice as opposed to solely being bound to the brave/Sass package.

I'm glad it helped though - and I hope other's can see the trace more clearly now. It was a funny patch of events:

- the most downloaded sass package was seemingly abandoned by the creator
- brave forked it, updated it and then after a year, package control switched to using that fork as the official source
- the fork contained a change to scope

**Comment by skyronic** [comment]
Thanks for letting us know. Currently there's no straight forward way to
support both extensions. I realized that the change would break for those
who are not using the new extension. But it looks like far more people are
using the new sass extension. You can still download an older version and
install it yourself. I'll set aside some time in the weekend to look into
finding a fix or a workaround.

**Comment by skyronic** [comment]
Looked into the problem in a bit more detail. There's no clear way how we can dynamically decide which scope to select and use.

Looks like there's two SCSS based extensions: https://packagecontrol.io/packages/SCSS and @braver's

While @braver's [reasoning about the change](https://github.com/braver/SublimeSass/issues/15#issuecomment-434614411) does make some sense, it's put us in an awkward state at this point.

@braver would you be open to keeping the old scope name for the time being until we can figure out a stable solution?

**Comment by braver** [comment]
@skyronic that is a possibility. It's something I contemplated before, maintaining compatibility with the css syntax for features like completions is tricky anyway. Looks like this is another case where it's perhaps not the easiest approach. I'll look into it, it probably just entails copying over the css completions and keybindings. Not a big problem, just more maintenance overhead for me.

**Comment by braver** [comment]
@skyronic Ok, let's do it. I'm about to release 2.1.0 of Sass that will switch it back to source.scss.

**Comment by skyronic** [comment]
@braver that's great to hear. Thank you. I'll make a new release reverting the last change as well.

**Comment by skyronic** [comment]
New release out. Hopefully this should support the new extension and the older one as well. Thanks again for your quick response, and helping with this situation @braver.

**Comment by braver** [comment]
No problem, I caused the situation in the first place 😂

**Comment by assembledadam** [comment]
Hey - since this change i've also noticed when I use sublime's comment shortcut (CMD+/) it uses the wrong type of comments within the SCSS block. Worked fine before!
