### ISSUE TITLE
yaml-macros should not be packed

### ISSUE THREAD

**Issue by Shigma** [vuejs/vue-syntax-highlight#167]
yaml-macros file is the source file and sublime-syntax is the generated one. In my opinion, to "gitignore" the *sublime-syntax* file and to "no-sublime-package" the *yaml-macros* file is a better practice.

**Comment by FichteFoll** [comment]
Not really an option. If the built file was excluded, then every installation would have to build manually with YAML Macros, which is an absolute no-go UX-wise.

**Comment by skyronic** [comment]
Thanks for clarifying @FichteFoll 

@Shigma you're right in the sense that it doesn't make sense to have a repo contain a generated file, but that is better for projects you have to compile/build. Github repos are used as sources for package control. 

It's the same way you will find [compiled JS and CSS files for vue](https://github.com/vuejs/vue/tree/dev/dist) but this is used for npm.
