### ISSUE TITLE
having Function as object value breaks highlighting

### ISSUE THREAD

**Issue by titarenko** [vuejs/vue-syntax-highlight#172]
![example](https://d1ro8r1rbfn3jf.cloudfront.net/ms_177595/ZzpMqxiHRSGK8XW1MB1Ic8yzpjr3Bi/index.vue%2B%25E2%2580%2594%2Bcrm-ui-kit.png?Expires=1543904035&Signature=mPeT1y1rnZFooPf5xufbRB-79a3IM3fWI8LSv6KJ7O7fl7vFAOm8RFOrAmp7PDahQIR-t85IrJv1CAoqYDAKCGnn4rWa6lBLbAsb6RGRnf~EdL8jZQldU~CJS8O01~04gIHtS1uy7qmpGuIomoS~Hy7-vaqGtbJsHyvQYtOO1ahsDoI8h5lM7dA7iOW~vUiy-mzrh92tI~FRq9wfFK2AsvHP4I6G6kC7pSKOxGEokE3gxh7V4~LgDm7mP6An1ntkyAk70pS7cHcj1da0Ve7AyL~Yq3OHdwYQvVmzkfS8LLullbDwFEYviwwhIs3nxCb1tICLSlwWeHGmmxrg9iK0iA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by FichteFoll** [comment]
The example is not accessible anymore. #216 should have fixed most (if not all) of these issues; please report again if the issue occurs there as well.
