### ISSUE TITLE
After Mac OSX 10.14.3 update, syntax errors on whole Vue component

### ISSUE THREAD

**Issue by nishman** [vuejs/vue-syntax-highlight#179]
After a Mojave 10.14.3 update 2 days ago, all of my Vue components have syntax error highlights on every line of the file. 

Mac OSX Mojave 10.14.3
Sublime v3.1.1, Build 3176
Vue Syntax Highlight v3.3.4

The files don't open with syntax errors, but as soon as I make a change, the whole file lights up with red lines.

![screenshot 2019-02-20 14 30 08](https://user-images.githubusercontent.com/5606951/53129292-0b82f900-351c-11e9-8e62-cc95dfe77c1b.png)

I tried reinstalling the plugin, then reinstalled Sublime itself, but I keep getting the issue. It only happens on `.vue` files when the plugin is installed.

Sometimes I see error messages when hovering over parts of the file. Here are some examples:

Template:
- Attributes:
> Cannot find name 'slot'
> Cannot find name 'title'
- Tags
> Operator '>' cannot be applied to types 'string' and '{}'
> Operator '>' cannot be applied to types 'boolean' and 'number'

Script:
- Anywhere
> Operator '<' cannot be applied to types '{ mounted(): void; }' and 'RegExp'.

Scss:
- Style tag
> Cannot find name 'style'
- Properties
> The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.
> Cannot find name 'margin'

**Comment by nishman** [comment]
Looks like the third time nuking and reinstalling Sublime seemed to fix it. For anyone else interested, these are the steps I took:

- Delete Sublime from the `Applications` folder
- Delete any `Sublime Text` folders inside `~/Library/Application Support/` (in my case, I had `Sublime Text 3` and also `Sublime Text 2` the first time)
- Reinstall the latest version of Sublime and the vue-syntax-highlight package
- Rinse and repeat...

**Comment by ilyasfoo** [comment]
Just to note, this also just happened to me on Windows 10. Reinstalled sublime fixed it.
