### ISSUE TITLE
Template-tag regex matches components prefixed "template"

### ISSUE THREAD

**Issue by abjugard** [vuejs/vue-syntax-highlight#183]
Current implementation of the `template-tag` regex matches Vue components with a `name` starting with the word "template". It is a simple fix for the new branch, and I have made a PR correcting it there.

**Comment by abjugard** [comment]
Here's some screenshots to illustrate my point.

Current behaviour:
![image](https://user-images.githubusercontent.com/287697/60175161-052ac380-9813-11e9-9fdd-bcbadc7fd178.png)

With my patch applied:
![image](https://user-images.githubusercontent.com/287697/60175197-1d9ade00-9813-11e9-85c9-4a08b59988ad.png)

**Comment by abjugard** [comment]
Yes, I see that my component can be simplified, not the point of this issue 😄

**Comment by skyronic** [comment]
Thank you for your fix!
