### ISSUE TITLE
Sublime package

### ISSUE THREAD

**Issue by sageworksstudio** [vuejs/vue-syntax-highlight#193]
```
Install
Via Package Control: search for Vue Syntax Highlight
```
Returns nothing.

**Comment by skyronic** [comment]
What version of sublime text do you use?

I can't seem to reproduce this. I see the package is live and available at [packagecontrol](https://packagecontrol.io/packages/Vue%20Syntax%20Highlight)

And works for me in sublime:

![image](https://user-images.githubusercontent.com/80173/73136594-3f647980-401d-11ea-9661-aa4be16c0b3b.png)

**Comment by sageworksstudio** [comment]
V3.2.2 Screenshots attached. It's weird that I'm not seeing it.
![version](https://user-images.githubusercontent.com/598105/73292259-96518680-41b6-11ea-8ebb-af4d46dbdedb.png)
![screenshot](https://user-images.githubusercontent.com/598105/73292272-9b163a80-41b6-11ea-954f-25cafd7cc563.jpg)

**Comment by skyronic** [comment]
Could you check the installed packages with this command:

![image](https://user-images.githubusercontent.com/80173/73306484-52787480-41ea-11ea-991e-bcff7165856a.png)

**Comment by sageworksstudio** [comment]
OK...feeling really dumb right about now. I'm using 2 different computers and it's installed on one and not the other. So of course I'm confusing which one and of course I can't install it on the machine that it's already installed on.

Nevermind, nothing to see here.

Thanks for your help.

**Comment by skyronic** [comment]
Glad it's sorted out! :)
