### ISSUE TITLE
ST4114 incompatibility

### ISSUE THREAD

**Issue by deathaxe** [vuejs/vue-syntax-highlight#213]
ST's HTML syntax had to change the way how CSS/JS syntax definitions are embedded within style and script tags in order to fix a core bug. It also requires changes to how those syntaxes are to be embedded. This change unfortunatelly effects all syntaxes, which inherit HTML.

Related PR: https://github.com/sublimehq/Packages/pull/2831

This broke VUE syntax.

A short look at this package revealed the following lines to be obsolete or not needed at all.

https://github.com/vuejs/vue-syntax-highlight/blob/6c3c26d6a022b2b4353e5a7f98c5e1496e9f7567/Vue%20Component.sublime-syntax#L191-L195

A backward compatible fix was to remove the context.

An inherited syntax needs to override `script-javascript-content` or `style-css-content` only, if it wants to embed a custom CSS/JS syntax (or scope), which is not the case here.

--- 

I'd suggest to take a look at...

https://github.com/sublimehq/Packages/blob/c70117be6402c54ccf860ab8edfcba8aade46c9e/ASP/HTML%20(ASP).sublime-syntax#L37-L67

This approach might be needed for all kinds of embedded script syntaxes to ensure toggle comment is working on the first and last line properly.

**Comment by rchl** [comment]
Can be closed now?

Thanks for fixing it @deathaxe btw!
