### ISSUE TITLE
Splitting off the Sublime Text syntax definition into a separate repo

### ISSUE THREAD

**Issue by FichteFoll** [vuejs/vue-syntax-highlight#226]
This repo currently primarily aims to provide a `tmLanguage` syntax definition file for Linguist and the old Sublime Text. Since the current Sublime Text version has already been moved to a separate `st4` branch with an entirely different file format and there not having been any activity on the main branch for over 5 years with some PRs for the `st4` branch still open and unreviewed (#222, #223), I have concluded that it makes the most sense to spit off the `st4` branch into a new project that the Sublime Text community can maintain by itself. Most of the open issues about highlighting in ST have also been fixed already but not closed.

The location of this new repository is: https://github.com/SublimeText/Vue

Over the next few days, I intend to complete the initial migration (https://github.com/SublimeText/Vue/pull/2), pull in the already proposed changes, create a new release and propose to change the "Vue Syntax Highlighting" entry on Package Control to direct to this new repository.

I also plan to make a few changes that I have already been thinking of but held back for now.

Just to be clear: **You don't need to do anything.** You *may* object to the Package Control replacement, according to the takeover procedure on that repository, but if you agree with my proposal you can already do so in this issue and it will shorten the takeover process. I will also let you know in this issue when this process has been completed.

**Comment by FichteFoll** [comment]
PR for the Package Control replacement: https://github.com/wbond/package_control_channel/pull/9008

**Comment by deathaxe** [comment]
First release in new home: https://github.com/SublimeText/Vue/releases/tag/4126-5.0.0

**Comment by FichteFoll** [comment]
The PC replacement has been completed.
