### ISSUE TITLE
Can't support indentedSyntan for Sass

### ISSUE THREAD

**Issue by xunjianxiang** [vuejs/vue-syntax-highlight#32]
![image](https://cloud.githubusercontent.com/assets/12422146/12350390/b7eaf20c-bbb1-11e5-8c18-5e0ac9c58c6f.png)

Editor: Sublime Text 3

An error here!

There is no hignlight!

What can I do?

Configure some what?

**Comment by yyx990803** [comment]
Fixed in 2.1.0
