### ISSUE TITLE
lang="coffee" or lang="coffeescript"?

### ISSUE THREAD

**Issue by kxxoling** [vuejs/vue-syntax-highlight#33]
``lang="coffee"`` won't set syntax highlighting, while ``lang="coffeescript"``will raise an error ``Module not found: Error: Cannot resolve module 'coffeescript'``. So would there add ``lang="coffee"`` support?

**Comment by azamat-sharapov** [comment]
`lang="coffee"` works for me. Make sure to use double quotes, instead of single.

**Comment by kxxoling** [comment]
@azamat-sharapov I'm sure it's double quotes. I'm trying to upgrade Sublime Text plugins first but occurred with some trouble. Will submit more info after upgradeing finished.

**Comment by kxxoling** [comment]
Both ``scss`` and ``coffee`` works now after upgrading:

![2016-01-18 6 36 19](https://cloud.githubusercontent.com/assets/1227139/12389284/af307bd8-be12-11e5-9224-5a4029f76a4b.png)

But no good as other parts. Am I missing some configures?
