### ISSUE TITLE
setting: scss mode

### ISSUE THREAD

**Issue by meodai** [vuejs/vue-syntax-highlight#34]
![screen shot 2016-01-31 at 16 55 23](https://cloud.githubusercontent.com/assets/608386/12703127/7d97d99e-c83b-11e5-9f70-9c413b8e398a.png)

when using `<style lang="sass">` would be awesome if 'scss' could be specified as syntax.

**Comment by azamat-sharapov** [comment]
Works for me. Can you open raw .scss file and see if highlights fine?

**Comment by meodai** [comment]
yes it does. I found the issue. On top of using the SASS sublime package I had one called "SASS-Syntax".

**Comment by airtonix** [comment]
I get no highlighting at all.

![screenshot from 2016-02-12 09-07-58](https://cloud.githubusercontent.com/assets/61225/12993091/250a1afe-d168-11e5-83c2-8badce3d44ee.png)


![screenshot from 2016-02-12 09-05-43](https://cloud.githubusercontent.com/assets/61225/12993092/2651fe9a-d168-11e5-888f-50d94dfb5177.png)

**Comment by thgh** [comment]
@airtonix same here, solution is to install "SASS" package. Also noticed that it's actually mentioned in the readme. Should probably be mentioned higher up.

**Comment by shealan** [comment]
Thanks for the tip! Adding the SASS package fixed it. Must have missed in the docs.

**Comment by Hidejec** [comment]
SASS package works for me, thanks!
