### ISSUE TITLE
LESS Highlighting

### ISSUE THREAD

**Issue by moe-szyslak** [vuejs/vue-syntax-highlight#35]
Less syntax breaks on some cases, especially when nesting.

![vue-sublime](https://cloud.githubusercontent.com/assets/2365328/12909198/a4912d5e-cf0f-11e5-891d-c2e26b94786d.png)

**Comment by moe-szyslak** [comment]
Hello @yyx990803, seems the culprit in the syntax highlighting is the [MaterialTheme] (https://github.com/equinusocio/material-theme) I've installed, not Vue syntax highlighting. Apologies for any inconvenience i've caused.

I guess the theme installs `Less` syntax highlighting and becomes the default highlighter for `.less` extensions, causing the havoc.

![material](https://cloud.githubusercontent.com/assets/2365328/13638234/6ccd8736-e61c-11e5-86bd-4a493b6a4108.jpg)

**Comment by prog-rajkamal** [comment]
@moe-szyslak thanks a lot for posting the solution.
I suffered from this issue from last week. I didn't even check if problem existed elsewhere.
