### ISSUE TITLE
New php files being set to Vue Component syntax

### ISSUE THREAD

**Issue by rawcreative** [vuejs/vue-syntax-highlight#39]
When creating a new php file in Sublime (Build 3103), if php content is pasted into the file before any other content is created, the file automatically gets it's syntax set to Vue Component, which is obviously incorrect since it's not a .vue file. 

While I've only played with creating syntax files in sublime, I'm pretty sure this is due to these lines here: https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.tmLanguage#L9-L10 which are looking at the first line to see if it's doctype, html or php tags. I'm unsure why this is included in the syntax file since none of those three are tags that would represent a .vue component file.

**Comment by didioh** [comment]
+1 
This is still an issue (Sublime Text Version 3.0 Build 3143)
