### ISSUE TITLE
Emmet completions not supported inside <style lang="*"></style>.

### ISSUE THREAD

**Issue by degorov** [vuejs/vue-syntax-highlight#40]
Don't even know if this issue should be posted here or in the [emmet-sublime](https://github.com/sergeche/emmet-sublime) repository. But completions DO work with pure stylus or less files.

To reproduce:
```
<style lang="stylus">
    body
        m0  <-- press TAB here and nothing happens
</style>
```

**Comment by nkCoding** [comment]
I can confirm this issue.
`Ctrl + E` works in this case, but that's not convenient enough.

I'd like to add [Vuejs Complete Package](https://github.com/BrainBuzzer/vuejs-sublime-complete)'s behavior just for reference. That package makes `tab` work for stylus completion, but fails in creating new line with `enter`  (as described in this [issue](https://github.com/billymoon/Stylus/issues/70#issue-135491457)). Vuejs Complete Package also fails to highlight jade snippets.

**Comment by jpokrzyk** [comment]
@nkCoding this PR https://github.com/vuejs/vue-syntax-highlight/pull/38 will fix the stylus enter key newline issue. 

@degorov unfortunately it doesn't fix the emmet tab complete. But if you change https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.tmLanguage#L286
from `source.vue-stylus.embedded.html` to `source.sass.embedded.html` making sublime think the stylus is sass code the tab complete for the emmet plugin works.

So you probably need to close this and open one over at https://github.com/billymoon/Stylus.

**Comment by yyx990803** [comment]
This should be fixed in the latest version with the stylus package upgrade.
