### ISSUE TITLE
Error highlighting on multiple cases in v-if

### ISSUE THREAD

**Issue by dargue3** [vuejs/vue-syntax-highlight#42]
I've noticed that Sublime highlights ```&&``` as if there is an error when you are putting multiple conditions in a ```v-if``` statement... is this a bug or are we not supposed to use this in Vue?

![screen shot 2016-04-07 at 21 53 32](https://cloud.githubusercontent.com/assets/13652794/14372105/75445362-fd0b-11e5-9a0e-a3295530f907.png)

**Comment by yyx990803** [comment]
HTML highlighter thinks you should escape it with `&amp;`. But it's fine, just ignore it...

**Comment by azamat-sharapov** [comment]
BTW, very annoying. Any easy way to fix this via vue-syntax-highlight package?

**Comment by yyx990803** [comment]
Should be fixed now.
