### ISSUE TITLE
对没有加引号的属性没有高光效果

### ISSUE THREAD

**Issue by graysheeep** [vuejs/vue-syntax-highlight#43]
![vue-highlight](https://cloud.githubusercontent.com/assets/4529986/14407110/bb302d7a-feef-11e5-8557-12657adf9b45.png)
我看看能不能自己改改看。

**Comment by q1cha0** [comment]
目前使用 element UI 的时候, 也遇到了这个问题, 请问你解决了么?

**Comment by skyronic** [comment]
This is working properly now. We will be releasing a new version soon which should have this included.

I'm closing this issue now, please feel free to re-open the issue if you continue experiencing problems.

![image](https://user-images.githubusercontent.com/80173/39843159-d6959a72-53b7-11e8-974f-b3bad6c43dec.png)
