### ISSUE TITLE
请教：在sublime 3中，es6高亮问题

### ISSUE THREAD

**Issue by 28240885** [vuejs/vue-syntax-highlight#47]
因为sublime 3默认的js语法高亮好像对es6支持的不太好，比如 
export default {
     data () {
           //.........
    }
}
这里的 data 是白色的没有颜色）

我的sulime安装了babel插件，单独的js文件，可以切换到 Javascript(babel)，但当写Vue Component时，只能用默认的高亮，这时 data JSON Array等都是无颜色的。怎么解决呢？

谢谢

**Comment by yyx990803** [comment]
把 babel 设置为 js 的默认高亮。

**Comment by easonzhang2015** [comment]
@yyx990803 如何把babel设置为默认高亮？

**Comment by LongYue9608** [comment]
@denver23  你怎么解决的。
