### ISSUE TITLE
Anything following jade loses syntax

### ISSUE THREAD

**Issue by tremendus** [vuejs/vue-syntax-highlight#5]
There is a small bug in the syntax highlighting when using jade templates

Anything following the close of the template tag has incorrect or inconsistent colors, eg: 

```
<!-- template -->
<template lang="jade">
...
</template>

<style lang="stylus">
@import '../shared'
.complete 
	text-decoration line-through
</style>
```

... offers different stylus syntax highlighting than: note the `@import` statement

```
<!-- template -->
<template>
...
</template>

<style lang="stylus">
@import '../shared'
.complete 
	text-decoration line-through
</style>
```

of course this is with stylus and jade syntax highlighting installed in ST3

![screen shot 2015-07-24 at 5 12 24 pm](https://cloud.githubusercontent.com/assets/5451510/8886934/35fdb2d4-3227-11e5-8c8f-e9042fa08044.png)
![screen shot 2015-07-24 at 5 12 33 pm](https://cloud.githubusercontent.com/assets/5451510/8886935/38518ea2-3227-11e5-9035-111e6e8a93ef.png)

**Comment by yyx990803** [comment]
Should be fixed now in 2.0.0
