### ISSUE TITLE
Syntax highlight for postcss

### ISSUE THREAD

**Issue by nicolasparada** [vuejs/vue-syntax-highlight#51]
Please, add the option to set the style lang to postcss, pcss and sss ([SugarSS](https://github.com/postcss/sugarss)).

**Comment by NicolasParada** [comment]
I know that there is still no syntax highlighter for sugarss [#11](https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS/issues/11)

**Comment by Kingdaro** [comment]
The syntax highlighting from the pull request doesn't seem to be working for me. And I have the PostCSS syntax installed.

![](http://a.pomf.cat/vhiwfz.png)

As you can see, it's messing up the rest of the syntax after the end style tag. Not too pleasant.

**Comment by wprater** [comment]
its has yet to be released.  you need to clone the package manually.

**Comment by wprater** [comment]
when I set the lang to postcss, I get an error in vue-loader trying to load a module.

`...is not a PostCSS plugin`

**Comment by kodekrendel** [comment]
What's the point if PostCSS not working with vue-loader?

**Comment by skyronic** [comment]
I believe postcss is now supported in the extension. Closing this issue.
