### ISSUE TITLE
Supporting Pug highlight

### ISSUE THREAD

**Issue by JasinYip** [vuejs/vue-syntax-highlight#54]
Jade is now renamed to Pug, see the issue: https://github.com/pugjs/pug/issues/2184

**Comment by monocles** [comment]
+1

**Comment by JasinYip** [comment]
Now we could install `Pug` package in Sublime's Package Control, then we will see Pug's highlight in `.vue` file.

**Comment by mdsb100** [comment]
@JasinYip what`s about vs code?

**Comment by JasinYip** [comment]
> @JasinYip what`s about vs code?

I'm not a vs code user so I have no idea about it...

**Comment by inselmensch** [comment]
![image](https://user-images.githubusercontent.com/3304771/80509211-619dc880-8979-11ea-91ca-77a9820db99f.png)

sadly here is something broken. as soon as i put the colon before "class" it destroys the highlighting. @JasinYip

**Comment by JasinYip** [comment]
@inselmensch This issue is talking about the renaming process. I think it would be better to create a new issue to report the bug and reference the author of the plugin😄
