### ISSUE TITLE
Not working at all in 3114

### ISSUE THREAD

**Issue by lunelson** [vuejs/vue-syntax-highlight#56]
Not sure if I'm missing a component, but this is not working at all for me. Could it be a problem with the latest version of Sublime? There seem to also be some problems rendering `jade` blocks in [Markdown Extended](https://github.com/jonschlinkert/sublime-markdown-extended) too; though `scss` still works fine there

![untitled](https://cloud.githubusercontent.com/assets/1242864/16042390/b7b516b4-323a-11e6-8b70-d1f5e148bc76.png)

**Comment by yyx990803** [comment]
Did you set the file type correctly? It's working properly for me in OS X build 3114.

**Comment by lunelson** [comment]
I created a new user, and a minimal setup of sublime with this plugin, the [tomorrow color schemes](https://github.com/theymaybecoders/sublime-tomorrow-theme), and the `jade` and `pug` plugins from [davidrios](https://github.com/davidrios); I get the following in 3114

![vue-test-2](https://cloud.githubusercontent.com/assets/1242864/16070466/ebed7d68-32d5-11e6-8f47-76a68569c2ad.png)

**Comment by lunelson** [comment]
P.S. also tried some of the default color schemes; still no highlighting inside the `<template>` blocks

**Comment by arbipher** [comment]
@lunelson try using " instead of ' around jade
`<template lang="jade">` seems working for me.

not familiar with sublime plugin but I think single quote mark ' is common in html-like files
@yyx990803 how about adding support for single quote mark '

**Comment by lunelson** [comment]
@arbipher thanks that seems to do the trick. I should have known to try that 😏
