### ISSUE TITLE
ES6 syntax incorrect highlight

### ISSUE THREAD

**Issue by Darkside73** [vuejs/vue-syntax-highlight#59]
```let``` and strings in back-ticks aren't  highlighted properly:

![2771215460](https://cloud.githubusercontent.com/assets/339596/16480798/d78b01ce-3eb0-11e6-8cdb-c10280346c93.png)

Sublime Text 3 build 3114
vue-syntax-highlight is up to date

**Comment by routegroup** [comment]
@Darkside73 were you trying on different color scheme?

**Comment by Darkside73** [comment]
Yes (default Monokai). Same results

**Comment by routegroup** [comment]
I tried to reproduce that (fresh install + this package) and it shows correctly. I guess some package is making some mess. Try "Package Control: Upgrade / Overwrite All Packages" or sth like that cause package is working correctly.

**Comment by Darkside73** [comment]
I've figured out. The problem was in https://github.com/int3h/sublime-better-javascript plugin.
Thanks)
