### ISSUE TITLE
Weird behavior when using class

### ISSUE THREAD

**Issue by victorwpbastos** [vuejs/vue-syntax-highlight#60]
When using the word `class` inside templates attributes, this happens:

![screenshot_1](https://cloud.githubusercontent.com/assets/1017515/16669961/669be91a-446e-11e6-95a5-1077f9f0a06d.png)

And the highlighter handles the `script` content as if it is a template content.

**Comment by yyx990803** [comment]
`class` is a JavaScript keyword, you should avoid it in expressions.

**Comment by terranc** [comment]
也遇到这样的问题，虽然class是javascript的关键词，但还是希望不要让高亮影响

**Comment by skyronic** [comment]
This is working properly now. We will be releasing a new version soon which should have this included.

I'm closing this issue now, please feel free to re-open the issue if you continue experiencing problems.

![image](https://user-images.githubusercontent.com/80173/39842981-f553211a-53b6-11e8-91a5-b9707460392e.png)
