### ISSUE TITLE
请问配图中 Sublime Text 配色主题是什么？

### ISSUE THREAD

**Issue by huangyangme** [vuejs/vue-syntax-highlight#61]
请问配图中 Sublime Text 配色主题是什么？

**Comment by monopieces** [comment]
Oceanic Next

**Comment by huayutiantian** [comment]
请问这个怎么安装到sublime中呢？

**Comment by ryh** [comment]
@huayutiantian Lets Google it for you [https://www.google.com/search?q=oceanic+next+sublime+text](https://www.google.com/search?q=oceanic+next+sublime+text)
or[ Bing](https://www.bing.com/search?q=oceanic+next+sublime+text)
