### ISSUE TITLE
seems no highlight for jade and scss

### ISSUE THREAD

**Issue by riotkkwok** [vuejs/vue-syntax-highlight#63]
![gh1](https://cloud.githubusercontent.com/assets/10059303/17368185/894489ba-59c5-11e6-914f-ebac914094e2.PNG)

ST2, already installed SCSS and Jade Syntax Plugins

![gh2](https://cloud.githubusercontent.com/assets/10059303/17368315/ff680db0-59c5-11e6-9ffb-0de45d70a72a.png)

**Comment by riotkkwok** [comment]
finally it works after I did some changes in **vue.tmLanguage**

```
<string>text.jade</string>  ==>  <string>source.jade</string>
<string>source.sass</string>  ==>  <string>source.scss</string>
```

**Comment by alberto2000** [comment]
How to adapt this fix to ST3?

**Comment by alberto2000** [comment]
Any help on this? I'd be happy to submit a PR with a fix if I could be pointed towards an initial direction on how to do the ST2 fix for ST3

**Comment by selfcatering** [comment]
this definitely works for ST3 so until it's merged just manually extract contents of Vue Syntax Highlight.sublime-package and make changes @riotkkwok suggested

**Comment by b3ntly** [comment]
Still having this issue but I resolved it by manually selecting view > syntax > jade on all Vue files. Syntax highlighting remains for <script> and <style> tags but the jade code gets properly highlighted. Template tag is <template lang="jade"> as recommended above.

**Comment by skyronic** [comment]
This is working properly now. We will be releasing a new version soon which should have this included.

I'm closing this issue now, please feel free to re-open the issue if you continue experiencing problems.

![image](https://user-images.githubusercontent.com/80173/39842842-40d1aad6-53b6-11e8-9700-1122a15fb33b.png)
