### ISSUE TITLE
Components named `<script-*>` break the highlighting

### ISSUE THREAD

**Issue by deiucanta** [vuejs/vue-syntax-highlight#68]
![image](https://cloud.githubusercontent.com/assets/2116280/18512222/bda6178c-7a90-11e6-95bc-d115d0f25ce7.png)

**Comment by alvin-nt** [comment]
I can confirm this one

**Comment by pythonz1943** [comment]
I can confirm this is also happening on me

**Comment by skyronic** [comment]
Will look into this issue and fix it if it's still present on the latest version

**Comment by tpv-ebben** [comment]
Duplicated by #102 and #93 
Standard SublimeText HTML highlighter correctly highlights custom components with dashes.

**Comment by skyronic** [comment]
Apologies for delay in following up.

This is working properly now. We will be releasing a new version soon which should have this fixed.

I'm closing this issue now, please feel free to re-open the issue if you continue experiencing problems.

![image](https://user-images.githubusercontent.com/80173/39842155-690fcf6c-53b3-11e8-9306-c906c0ad783c.png)

**Comment by HitSong** [comment]
It occurs to me.
![image](https://user-images.githubusercontent.com/33504779/53592931-4945e880-3bd2-11e9-8b21-42f3d2e61921.png)
When I delete the code in script tag，the style part will be highlight show 
![image](https://user-images.githubusercontent.com/33504779/53593087-b9ed0500-3bd2-11e9-8280-e5779d3c898f.png)
when I write “export default” ,it goes wrong.
![image](https://user-images.githubusercontent.com/33504779/53593243-29fb8b00-3bd3-11e9-922b-841c612460b6.png)

**Comment by chenxiaoleizi** [comment]
I can confirm this is also happening on me

**Comment by chenxiaoleizi** [comment]
> 
> 
> It occurs to me.
> ![image](https://user-images.githubusercontent.com/33504779/53592931-4945e880-3bd2-11e9-8b21-42f3d2e61921.png)
> When I delete the code in script tag，the style part will be highlight show
> ![image](https://user-images.githubusercontent.com/33504779/53593087-b9ed0500-3bd2-11e9-8280-e5779d3c898f.png)
> when I write “export default” ,it goes wrong.
> ![image](https://user-images.githubusercontent.com/33504779/53593243-29fb8b00-3bd3-11e9-922b-841c612460b6.png)

I can confirm this is also happening on me
