### ISSUE TITLE
Better support ES6 Syntax

### ISSUE THREAD

**Issue by icetbr** [vuejs/vue-syntax-highlight#70]
This is something Sublime itself is lacking, and plugins such as JavaScript Next and Babel fix.

For instance the new method declaration is treated as a method call.

1) entity.name.function,js
function doStuff() {
}

2) meta.function-call.js
var ob = {
   doStuff() {
  }
}

In Next, they're called entity.name.method.js and entity.name.function.js

**Comment by yyx990803** [comment]
Just disable the built-in JavaScript package and vue files will use other JS syntax highlight packages.
