### ISSUE TITLE
Syntax highlight for JSX

### ISSUE THREAD

**Issue by jin5354** [vuejs/vue-syntax-highlight#71]
![da016a79-9fc4-4f0b-9253-4d41c7a20e00](https://cloud.githubusercontent.com/assets/6868950/19232251/4fdcab68-8f11-11e6-9d32-5bd0bda3c53b.png)

Please consider adding the support for JSX.

**Comment by taoche** [comment]
I also need... Please!!

**Comment by DearMadMan** [comment]
This is very helpful.

**Comment by jbruni** [comment]
Much welcome... I'm also entering the Vue+JSX adopters team...

**Comment by yyx990803** [comment]
The `<script>` block uses the syntax highlighting currently active for you normal `.js` files. To support JSX highlighting inside Vue files, just set [Babel javascript highlighting package](https://packagecontrol.io/packages/Babel), which supports JSX, as your default JS highlighting. **Note you may need to explicitly disable Sublime's default `JavaScript` package to make it work.**

**Comment by imns** [comment]
You should post this solution in the readme.
