### ISSUE TITLE
Subltime Text <style> coloring just stopped working?

### ISSUE THREAD

**Issue by vanderlin** [vuejs/vue-syntax-highlight#76]
![image](https://cloud.githubusercontent.com/assets/149997/21191693/a5b7d5b4-c1eb-11e6-9efe-e62a8698f71c.png)

**Comment by urbany** [comment]
@vanderlin did it get fixed for you?
Using latest version of vue-syntax-highlight I'm now getting scss errors again, looks like it is trying to parse as sass:
![screen shot 2017-01-27 at 18 50 47](https://cloud.githubusercontent.com/assets/50884/22383420/9caedcee-e4c1-11e6-8a76-310851b7bdc4.png)
