### ISSUE TITLE
想问一下配图代码的字体是什么？

### ISSUE THREAD

**Issue by u3u** [vuejs/vue-syntax-highlight#78]
![](https://cloud.githubusercontent.com/assets/499550/11458853/99ed23aa-9696-11e5-9bf6-43c706487aee.png)
难道是 Ubuntu Mono 么？

**Comment by MingGeng** [comment]
抱歉，这要问原图作者，我没用过这个主题/字体；

2017年1月9日 下午07:03，u3u <notifications@github.com> 写道：


难道是 Ubuntu Mono 么？

**Comment by yyx990803** [comment]
Hack

**Comment by u3u** [comment]
谢谢啦～
