### ISSUE TITLE
Stylus: cannot create newline by pressing Enter

### ISSUE THREAD

**Issue by azamat-sharapov** [vuejs/vue-syntax-highlight#8]
I thought this is something on my end, until my colleague told me he is having same problem. [Here is very similar issue](https://github.com/davidrios/jade-tmbundle/issues/54) I just found.

**Comment by matteocontrini** [comment]
Reported [here](https://github.com/billymoon/Stylus/issues/66) as well, not sure if it's related to this package or the Stylus package. There's a repro case in the linked issue.
