### ISSUE TITLE
broken syntax highlighting when using spread operator

### ISSUE THREAD

**Issue by philippkuehn** [vuejs/vue-syntax-highlight#81]
Syntax highlighting is completely broken when using the beautiful spread-operator.

<img width="700" alt="0dkhrscxtx" src="https://cloud.githubusercontent.com/assets/2500670/22670583/220bd940-ecca-11e6-8c90-2a8ede4a3a40.png">

**Comment by yyx990803** [comment]
If your have configured your normal JavaScript to use a highlighting package that supports this, then it's not being used for the script inside Vue files. Disable Sublime's default JavaScript package to make it work.
