### ISSUE TITLE
No syntax highlighting for single quote lang='' blocks

### ISSUE THREAD

**Issue by wopian** [vuejs/vue-syntax-highlight#82]
Opening this here as this is the grammar used by GitHub's [Linguist](https://github.com/github/linguist/blob/76d41697aaed6e0354202dd94e07d646c82dfe61/vendor/README.md) for Vue syntax highlighting on GitHub.

Using single quotes, Jade/Pug doesn't highlight at all and SCSS `@extend` and variables behave strangely as it uses the CSS grammar:
```vue
<template lang='jade'>
div
  if hello
    p Hello
    else
      p World
</template>

<style lang='scss'>
  @import '~styles/main.scss';
  section[role='alert'] {
    @extend .alert;
    background: $white;
  }
</style>
```

Using double quotes they are fine:
```vue
<template lang="jade">
div
  if hello
    p Hello
    else
      p World
</template>

<style lang="scss">
  @import '~styles/main.scss';
  section[role='alert'] {
    @extend .alert;
    background: $white;
  }
</style>
```

**Comment by wopian** [comment]
Using `lang="pug"` doesn't work at all. 

```vue
<template lang="pug">
div
  if hello
    p Hello
    else
      p World
</template>

<template lang="jade">
div
  if hello
    p Hello
    else
      p World
</template>
```

**Comment by tlgreg** [comment]
I confirm the later too, currently jade works, pug doesn't.

![vue-syntax-highlight-jade-vs-pug](https://cloud.githubusercontent.com/assets/666791/22855517/c15a9df0-f081-11e6-9b10-753fb3b68ae4.png)

Pug lang package is also installed, a file in pug syntax works.

**Comment by wopian** [comment]
cc @yyx990803
