### ISSUE TITLE
<script> should be excluded from scope: source.js.embedded.html (Sublime Text)

### ISSUE THREAD

**Issue by Rayraegah** [vuejs/vue-syntax-highlight#83]
Vue syntax wraps `<script>` tags in scope `source.js.embedded.html`.

![image](https://cloud.githubusercontent.com/assets/1559650/23070606/81e0f1c8-f523-11e6-9431-2153bd44771b.png)

while html syntax does not.

![image](https://cloud.githubusercontent.com/assets/1559650/23070812/362dfd06-f524-11e6-8ce4-4ac38c5c4418.png)

Reported the same issue in Riotjs syntax as well. https://github.com/riot/syntax-highlight/issues/4. Would be nice to have a fix, so I don't have to dirty check content in https://github.com/jonlabelle/SublimeJsPrettier/issues/18

**Comment by skyronic** [comment]
Hello, Looks like we've moved to `source.js` scope for some time now and I'll be closing this issue as it doesn't need any action from our end. Please feel free to reopen if there's anything else we can do.
