### ISSUE TITLE
in vue file scss can't highlight

### ISSUE THREAD

**Issue by ooEasonYi** [vuejs/vue-syntax-highlight#84]
i realy installed vue-syntax-highlight 
but  scss can't highlight
![image](https://cloud.githubusercontent.com/assets/18495963/23641348/0f0ae65e-032e-11e7-9862-4961f6687bcf.png)

**Comment by vanderlin** [comment]
you need to install [Sass package for sublime ](https://packagecontrol.io/packages/Sass)

**Comment by alberto-bottarini** [comment]
Confirm. Installing 'sass' package fixes this issue.
