### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by vanderlin** [vuejs/vue-syntax-highlight#85]
Trying to figure this out, but I am getting an annoying autocomplete bug when writing sass. Anytime I ass a semicolon it auto completes with snippets. Wondering if this is just my setup or are others having this issue? 
![image](https://cloud.githubusercontent.com/assets/149997/23660878/de10cf56-0318-11e7-9904-8fdc2485d673.png)

**Comment by skyronic** [comment]
Hello, this looks like it's an issue with a 3rd party extension (SASS perhaps). Vue's syntax highlight embeds the functionality of that extension.
