### ISSUE TITLE
Support for custom block

### ISSUE THREAD

**Issue by lionel-bijaoui** [vuejs/vue-syntax-highlight#87]
Hello,
I'm trying to make a `docs` custom block like in [the documentation](https://vue-loader.vuejs.org/en/configurations/custom-blocks.html). I'm also using sublime text 3.
How do I make sublime use the good syntax highlight and prettifier ?
I have indicated the `lang` attribute on my custom tag but it doesn't seem to do anything.
Is there yet a support for this functionality ?
Thank you for your help.

**Comment by skyronic** [comment]
By default, everything that's not in `template` or `script` or `style` is treated as regular html. The `lang` attribute won't have support in any other tags.

**Comment by Cobertos** [comment]
Is there guidance on how we might extend the syntax for our own uses for custom blocks? I have a <test> block that would really benefit from js syntax highlighting.

I noticed [Sublime has syntax inheritance](https://www.sublimetext.com/docs/syntax.html#inheritance) but only in the private beta of v4. Not sure how it's done or if possible in v3 but figured I'd ask.
