### ISSUE TITLE
Could include JSX syntax?

### ISSUE THREAD

**Issue by boringer** [vuejs/vue-syntax-highlight#90]
I know now I can enable JSX highlighting with package of Babel, but in Sublime Text, I must ignore default JS package first to make that work, that means I will lose all features (such as auto complete) provided by default JS package.

**Comment by borela** [comment]
Use https://github.com/borela/naomi instead, it'll enable JSX support + other javascript extensions.

**Comment by skyronic** [comment]
This isn't specifically an issue of the syntax plugin since we can't bundle an entire JS syntax implementation. You can optionally open issues with Babel/Sublime to add functionality that you might be missing with each packages.
