### ISSUE TITLE
Silly question: What's that color scheme?

### ISSUE THREAD

**Issue by Herteby** [vuejs/vue-syntax-highlight#91]
It looks pretty sweet!

**Comment by longthanhtran** [comment]
I think it is [Oceanic Next Color Scheme](https://github.com/voronianski/oceanic-next-color-scheme). You may try see if it works for you :)

**Comment by Herteby** [comment]
I figured it out, it's an old version of Material Theme. Evan You forked it:
https://github.com/yyx990803/material-theme/blob/master/schemes/Material-Theme.tmTheme
