### ISSUE TITLE
Incorrect syntax highlighting for some element names, for example <b-woot>

### ISSUE THREAD

**Issue by Herteby** [vuejs/vue-syntax-highlight#93]
If an element name begins with a standard HTML name and a dash, the part after the dash shows up as an attribute-name instead of a tag-name. I found this out working with Buefy, which uses b- as it's prefix.

![image](https://cloud.githubusercontent.com/assets/6474685/26577042/43b26ee2-452b-11e7-95c0-96d373430194.png)

**Comment by skyronic** [comment]
This is working properly now. We will be releasing a new version soon which should have this included.

I'm closing this issue now, please feel free to re-open the issue if you continue experiencing problems.

![image](https://user-images.githubusercontent.com/80173/39843119-a6e338fc-53b7-11e8-8de2-0d7871a2b586.png)
