### ISSUE TITLE
support typescript

### ISSUE THREAD

**Issue by ije** [vuejs/vue-syntax-highlight#97]
Hello,
I'm writing a project with webpack 2 + typescript 2, i had built the project according the TS official Vue tutorial at [https://github.com/Microsoft/TypeScript-Vue-Starter](https://github.com/Microsoft/TypeScript-Vue-Starter), and i can build the project by webpack and it work fine, but the typescript(`<script lang="ts">`) in .vue file just have the js syntax highlight and i want it can be parsed by the official Typescript sublime text plugin.
so is there a plan to support typescript?
Thanks!

**Comment by ije** [comment]
anyway, i have switch to the vscode with vetur plugin, it work fine.

**Comment by tommitytom** [comment]
I would also like to see TypeScript support!  The official TypeScript syntax highlighter is pretty good: https://github.com/Microsoft/TypeScript-Sublime-Plugin

**Comment by django-wong** [comment]
Can we reopen this issue?
+1 for typescript support

**Comment by ilearnio** [comment]
Can't believe Vue implemented TypeScript support but forgot about Sublime users 😢. This should be reopened
