### ISSUE TITLE
Syntax in `<script type="text/ecmascript-6"></script>` cannot highlight

### ISSUE THREAD

**Issue by ickedesign** [vuejs/vue-syntax-highlight#99]
![pic](https://segmentfault.com/img/bVQf9t?w=1366&h=768)
I have install the Vue Syntax Highlight and the syntax in`<script></script>` can highlight normally.
But it can't work in  `<script type="text/ecmascript-6"></script>` .
Could u tell me how to handle it?thx

**Comment by yyx990803** [comment]
Why would you add the `type` at all? Sublime doesn't need that to work.

**Comment by frellica** [comment]
The type might be added by webstorm editor automatically.
Found it in my colleage's code

**Comment by 82tuskers** [comment]
I probably found an easy way to get this working: First `manually` install the Vue Syntax Highlight package and then [here](https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.tmLanguage#L832) just add `|ecmascript-6` after `javascript|babel`. Restart ST3 and then you will have this working.

**Comment by skyronic** [comment]
This is working properly now. I'm closing this issue now, please feel free to re-open the issue if you continue experiencing problems.

![image](https://user-images.githubusercontent.com/80173/39842337-160a6484-53b4-11e8-98d0-f8c1adb75625.png)
